### PR TITLE
Add webhook import

### PR DESCRIPTION
**Pull request by Teko012**
Add webhook import into state file

### CODE REVIEW

**Comment by Teko012** [comment]
@wgebis If you can also test it, that would be great :)

**Comment by Teko012** [comment]
@wgebis Is it possible to test and review this? :)

**Comment by Szasza** [comment]
@Teko012 thank you for your contribution. I will review and test it over the weekend.

**Review by Szasza — APPROVED** [review]
Looks good, however there are some unrelated cleanup changes. It is usually best to have the changeset reflect the planned changes only, otherwise it is easy to sneak in unintended bugs.

**Comment by Teko012** [comment]
@Szasza Thank you! Is it possile to make a release?

**Comment by Szasza** [comment]
@Teko012 I cannot create a release, only @wgebis can.

**Comment by Teko012** [comment]
@wgebis Can you create a release? :)

**Comment by Teko012** [comment]
@wgebis Any updates on a possible release?

**Pull request merged**
