### PR TITLE
adding click_tracking support, updating documentation on open_tracking availability

### LINKED ISSUE #52: Add support for argument and attribute "click_tracking" in resource and data source "mailgun_domain"
### Terraform Version
`v1.6.4`

### Affected Resource(s)
- Resource `mailgun_domain`
- Data source `mailgun_domain`

### Terraform Configuration Files
```hcl
# Create a new Mailgun domain
resource "mailgun_domain" "default" {
  name          = "test.example.com"
  click_tracking   = "yes"
  web_scheme = "https"
}

data "mailgun_domain" "default" {
  name          = "test.example.com"
}
```

### Expected Behavior
- Have the `click_tracking` argument applied for the domain from the resource.
- Have the `click_tracking` attribute's value shown in the resource and data source's attributes.

### Actual Behavior
- Resource: The `click_tracking` argument is not supported.
- Data source: The `click_tracking` argument is not shown.

### References
- https://documentation.mailgun.com/en/latest/api-domains.html#domains

### PR DESCRIPTION
**Pull request by Szasza**
Closes #52

### CODE REVIEW

**Comment by wgebis** [comment]
Hi there! Thanks for contributing! 
Did you check acc tests?

**Comment by Szasza** [comment]
Hi @wgebis !

My pleasure, and thank you for maintaining the Mailgun provider. Yes, I ran the acceptance tests. There is one error in the test suite but it is unrelated to my change.

**Comment by Szasza** [comment]
Hi @wgebis ,

I hope all is well. I would like to ask if there is a chance to get this and #51 reviewed and if all good, then merged, and a new version of the provider tagged off.

Thank you in advance for your time, it is much appreciated.

**Comment by stevenatdomidocs** [comment]
+1, I am interested in this merge.

**Comment by Szasza** [comment]
Hi @wgebis,

Is there a chance to merge this and #51 anytime soon? Or maybe adding another user with merge privileges if your time is constrained?

Thank you in advance.

**Review by wgebis — DISMISSED** [review]

**Comment by wgebis** [comment]
Hi there, 
I merged #51 and I have also committed a minor fix in test: https://github.com/wgebis/terraform-provider-mailgun/commit/4726345d3a59bb5d6a13c7562b38baa9e6d1c7e4. So now master branch seems to be stable.  

I have just sent to you invite to this repo, so feel free to make a feature branch and contribute directly to this repo. Let me know then you have some code to review, I will run acc tests locally. When we will have this PR merged ans tested I will cut the new release. 

Best,
W

**Comment by wgebis** [comment]
BTW: there are some conflicts here, could you resolve them?

**Comment by Szasza** [comment]
Hi @wgebis ,

Thank you for the invitation and for the reviews and merge of #51 , it is much appreciated. Also I have updated this branch, the merge conflicts are resolved.

Could you please check the changes?

Thank you again.

**Review by wgebis — APPROVED** [review]

**Comment by wgebis** [comment]
@Szasza I still see the conflicts to need to be resolved 👇 .

**Comment by Szasza** [comment]
@wgebis it is not there 🤔 Is there a chance of needing to reload the page?

image

**Comment by wgebis** [comment]
OK, I wanted to make a rebase, but let's merge it.

Wojciech Gębiś
tel. 505122126

**Comment by wgebis** [comment]
Acc tests LGTM, I cut a new release: https://github.com/wgebis/terraform-provider-mailgun/releases/tag/v0.7.6

**Pull request merged**
