### PR TITLE
Fix #10 Add support for additional SMTP User

### LINKED ISSUE #10: Enhancement : add support for additional SMTP User
Hi

It would be great to add support of "additional SMTP User", aka domain credentials in API 

Thanks !

### PR DESCRIPTION
**Pull request by emeric-martineau**
This PR is about add support to create, update, delete a credential in domain.

Currently work-in-progess.

Help is welcome!

### CODE REVIEW

**Comment by AndrewChubatiuk** [comment]
@emeric-martineau 
region is redundant here, domain is unique across all regions, you cannot have domains with the same name in several regions

**Comment by emeric-martineau** [comment]
Hi @AndrewChubatiuk,
thanks for your help.

It's strange, when I create a domain in US, this domain is unknow on EU.

The password seem to be require: https://documentation.mailgun.com/en/latest/api-domains.html#domains.
I have try manually create credential without password, I have get bad request:
```
  curl -s --user "api:${api}" \
    "https://api.mailgun.net/v3/domains/${domain}/credentials" \
    -F "login=${email}" \
    -F "password="
curl: (22) The requested URL returned error: 400 Bad Request
```

**Comment by wgebis** [comment]
@emeric-martineau a pushed your branch to the main plugin repo: https://github.com/wgebis/terraform-provider-mailgun/tree/add_credential_support_origin
Could we continue further development from there? You should have the right permissions to access the repo and able to push changes. 
Let me know if it works 👍 .

**Comment by emeric-martineau** [comment]
@wgebis yes, it's ok for me. It's work.
But we need create a new PR.

**Comment by wgebis** [comment]
Great, so please create the new PR, I will close this one.

**Comment by wgebis** [comment]
@emeric-martineau @AndrewChubatiuk 
In terms of region, Mailgun provide completely different group of endpoints (https://api.mailgun.net/v3 vs https://api.eu.mailgun.net/v3) and probably also different of databases. Objects creates under EU is unknown ender US and vice versa. 
So one main consequences of this approach is that we have to provide the region in every resource created via Mailgun API. In other words, we are not able to explicitly obtain the region based on the domain name (we are able to do this by trail and error method iterates over the list of regions, but it's ultimately poor... ).

**Pull request closed without merging**
