### PR TITLE
feat: support accepted webhook

### PR DESCRIPTION
**Pull request by loeffel-io**
hey, we need to have accepted webhook support asap 

https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Webhooks/#tag/Webhooks/operation/httpapi.(*T).GetAllDomainWebhooks-fm-23

### CODE REVIEW

**Comment by loeffel-io** [comment]
ping @jwegis - please merge this, its a blocker on our end

**Review by Szasza — APPROVED** [review]

**Comment by Szasza** [comment]
@loeffel-io thank you for your contribution. Please note that only @wgebis can tag off and publish a new version of the provider.

**Comment by wgebis** [comment]
@loeffel-io @Szasza 
I cut the new release v0.7.7, job is running, within a couple of minutes new binary should be uploaded to registry. 
Thanks.

**Comment by loeffel-io** [comment]
Thanks guys ❤️

**Comment by Szasza** [comment]
@wgebis thank you 🙇🏻‍♂️

**Pull request merged**
