### PR TITLE
Add dkim selector when creating a new domain

### PR DESCRIPTION
**Pull request by elagree**
Description:
The PR adds the dkim_selector to the Domain Resource. This will helpful to create Mailgun domains when you need to specify a dkim_selector during the mailgun domain creation.

I also wanted to update the "resourceMailgunDomainUpdate" but it seems there is a problem due to the smtp_password which is "<nil>" so the test :

```
if currentData.Get("smtp_password") != newPassword {
		errc = client.ChangeCredentialPassword(ctx, smtpLogin, newPassword)

		if errc != nil {
			return diag.FromErr(errc)
		}
```

is failing and it's trying to change the password with the same value (which seems not possible on MailGun side).

It would be great to "allow" only the dkim_selector update without the recreation but it seems that the "smtp_password/nil problem" should be fix first

I also upgrade the MailGunSdk from v3 to v4.

Why didn't we update the data source?
The mailgun-go client used by this provider doesn't expose Dkim Selector in the DomainResponse.

Why are there no tests for DKIM Key Size?
I didn't see a test for the DomainCreate function. In the [MailGunApi](https://documentation.mailgun.com/en/latest/api-domains.html#domains) or in the [MailGunGoSdk](https://github.com/mailgun/mailgun-go) I didn't see any easy way to get the current dkim_selector for a current domain.

I don't know if I should use ImportStateVerifyIgnore or not.

A last word, I also encountered some issue with the resourceMailgunRouteCreate. I think it would be great to catch the ErrorMessage from the API and give it to the user as the generic message "Unavailable desc = transport is closing"" is not very helpful.

Thank you !

### CODE REVIEW

**Comment by elagree** [comment]
@wgebis Hello! I would very much appreciate your review/comments to this PR. Big thanks !

**Comment by wgebis** [comment]
@elagree thanks. I noticed that you have upgraded Mailgun go client, did you face any issues with the setting of default SMTP credentials in case of creating a domain?
As far I remember, v4 API doest support retrieving once created secret, so terraform is not able to compare password passed in `.tr` file with the remote one.

**Comment by elagree** [comment]
Hello @wgebis !
Thanks for your answer.

I didn't notice any issue on my side when creating a new domain. We are using your provider and add a ignore_changes for smtp_password since the beginning.

Thanks,
Regards

**Comment by elagree** [comment]
Hello @wgebis Do you know when you would be able to handle this request ?

Thank you

**Comment by wgebis** [comment]
@elagree please look at https://github.com/wgebis/terraform-provider-mailgun/pull/15
I moved your changes with update Terraform SDK as well.

**Pull request closed without merging**
